"""Add temp system about and faq

Revision ID: 6c8ca9be8a37
Revises: 21529dfe822f
Create Date: 2024-04-23 15:02:55.347354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8ca9be8a37'
down_revision: Union[str, None] = '21529dfe822f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=50), nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=25), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sensor_data', sa.Column('temp_1', sa.Float(), nullable=True))
    op.add_column('sensor_data', sa.Column('temp_2', sa.Float(), nullable=True))
    op.add_column('sensor_data', sa.Column('temp_3', sa.Float(), nullable=True))
    op.add_column('sensors', sa.Column('temp', sa.Float(), nullable=True))
    op.add_column('systems', sa.Column('area', sa.Float(), nullable=True))
    op.add_column('systems', sa.Column('fruit', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('systems', 'fruit')
    op.drop_column('systems', 'area')
    op.drop_column('sensors', 'temp')
    op.drop_column('sensor_data', 'temp_3')
    op.drop_column('sensor_data', 'temp_2')
    op.drop_column('sensor_data', 'temp_1')
    op.drop_table('notifications')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
